# Generated by Django 3.1.2 on 2020-11-15 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorty', '0003_auto_20201031_0623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id',
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='default@email.com', max_length=254, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
